DROP TABLE FORMUAL_SIMPTOME;

CREATE TABLE FORMUAL_SIMPTOME (
  doc1 VARCHAR2(4000)
)
ORGANIZATION EXTERNAL (
  TYPE oracle_loader
  DEFAULT DIRECTORY TRIALS
  ACCESS PARAMETERS (
    RECORDS
    XMLTAG ("Patient")
    FIELDS NOTRIM
    MISSING FIELD VALUES ARE NULL
  )
  LOCATION ('Formular_Simptome.xml')
)
REJECT LIMIT UNLIMITED;

SELECT * FROM FORMUAL_SIMPTOME;

SELECT PACIENT_ID,TO_DATE(DATA_FORMULAR,'DD-MM-YYYY') as DATA_FORMULAR,
      CHESTIONAR_1,CHESTIONAR_3,CHESTIONAR_4,CHESTIONAR_5,
      CHESTIONAR_6,CHESTIONAR_7,CHESTIONAR_8,CHESTIONAR_9,
      CHESTIONAR_10,CHESTIONAR_11,CHESTIONAR_12,CHESTIONAR_13,
      CHESTIONAR_14,CHESTIONAR_15,CHESTIONAR_16
FROM   FORMUAL_SIMPTOME x,
       XMLTABLE('/Patient'
         PASSING XMLTYPE(x.doc1)
         COLUMNS 
           "PACIENT_ID" NUMBER(4) PATH 'PACIENT_ID',
           "DATA_FORMULAR" CHAR(10) PATH 'DATA_FORMULAR' ,
           "VIZITA_NUMAR" INT PATH 'VIZITA_NUMAR',
           "CHESTIONAR_1" INT PATH 'Chestionar_1',
           "CHESTIONAR_2" INT PATH 'Chestionar_2',
           "CHESTIONAR_3" INT PATH 'Chestionar_3',
           "CHESTIONAR_4" INT PATH 'Chestionar_4',
           "CHESTIONAR_5" INT PATH 'Chestionar_5',
           "CHESTIONAR_6" INT PATH 'Chestionar_6',
           "CHESTIONAR_7" INT PATH 'Chestionar_7',
           "CHESTIONAR_8" INT PATH 'Chestionar_8',
           "CHESTIONAR_9" INT PATH 'Chestionar_9',
           "CHESTIONAR_10" INT PATH 'Chestionar_10',
           "CHESTIONAR_11" INT PATH 'Chestionar_11',
           "CHESTIONAR_12" INT PATH 'Chestionar_12',
           "CHESTIONAR_13" INT PATH 'Chestionar_13',
           "CHESTIONAR_14" INT PATH 'Chestionar_14',
           "CHESTIONAR_15" INT PATH 'Chestionar_15',
           "CHESTIONAR_16" INT PATH 'Chestionar_16'                 
         ) xt;
