
DROP USER PROJECTSIA CASCADE;

CREATE USER PROJECTSIA IDENTIFIED BY pswProject
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON USERS;

grant connect, resource to PROJECTSIA;
grant CREATE VIEW to PROJECTSIA;
grant CREATE ANY DIRECTORY to PROJECTSIA;
grant DROP ANY DIRECTORY to PROJECTSIA;

--drop table PROJECTSIA.INVESTIGATORI_TABLE;
CREATE TABLE PROJECTSIA.INVESTIGATORI_TABLE 
( INVESTIGATOR_ID NUMBER(4) ,
  NUME_INVESTIGATOR VARCHAR2(26))
ORGANIZATION EXTERNAL
  (  TYPE ORACLE_LOADER
     DEFAULT DIRECTORY TRIALS
     ACCESS PARAMETERS 
       (RECORDS DELIMITED BY NEWLINE 
           NOBADFILE
           NODISCARDFILE
           NOLOGFILE
           FIELDS TERMINATED BY ','
           MISSING FIELD VALUES ARE NULL
       )
     LOCATION ('Investigator.csv')
  )
  REJECT LIMIT UNLIMITED;
  
select * from PROJECTSIA.INVESTIGATORI_TABLE ;

--drop table PROJECTSIA.ORASE_TABLE;
CREATE TABLE PROJECTSIA.ORASE_TABLE 
( ORAS_ID     NUMBER(4) ,
  NUME_ORAS   VARCHAR2(30))
ORGANIZATION EXTERNAL
  (  TYPE ORACLE_LOADER
     DEFAULT DIRECTORY TRIALS
     ACCESS PARAMETERS 
       (RECORDS DELIMITED BY NEWLINE 
           NOBADFILE
           NODISCARDFILE
           NOLOGFILE
           FIELDS TERMINATED BY ','
           MISSING FIELD VALUES ARE NULL
       )
     LOCATION ('Orase.csv')
     )
  REJECT LIMIT UNLIMITED;
  
select * from PROJECTSIA.ORASE_TABLE ;

CREATE TABLE PROJECTSIA.PACIENTI_TABLE 
( PACIENT_ID      NUMBER(6),
  SPITAL_ID       NUMBER(4) ,
  INVESTIGATOR_ID NUMBER(4) ,
  VIZITA_1 DATE,
  VIZITA_2 DATE,
  VIZITA_3 DATE,
  VIZITA_4 DATE,
  VIZITA_5 DATE,
  VIZITA_6 DATE,
  VIZITA_7 DATE,
  VIZITA_8 DATE)
ORGANIZATION EXTERNAL
  (  TYPE ORACLE_LOADER
     DEFAULT DIRECTORY TRIALS
     ACCESS PARAMETERS 
       (RECORDS DELIMITED BY NEWLINE 
           NOBADFILE
           NODISCARDFILE
           NOLOGFILE
           FIELDS TERMINATED BY ','
           MISSING FIELD VALUES ARE NULL
           ( PACIENT_ID CHAR(10),
             SPITAL_ID CHAR(10),
             INVESTIGATOR_ID CHAR(10),
             VIZITA_1 CHAR(20) date_format DATE mask "DD-MM-YYYY",
             VIZITA_2 CHAR(20) date_format DATE mask "DD-MM-YYYY",
             VIZITA_3 CHAR(20) date_format DATE mask "DD-MM-YYYY",
             VIZITA_4 CHAR(20) date_format DATE mask "DD-MM-YYYY",
             VIZITA_5 CHAR(20) date_format DATE mask "DD-MM-YYYY",
             VIZITA_6 CHAR(20) date_format DATE mask "DD-MM-YYYY",
             VIZITA_7 CHAR(20) date_format DATE mask "DD-MM-YYYY",
             VIZITA_8 CHAR(20) date_format DATE mask "DD-MM-YYYY"
           )
       )
     LOCATION ('Pacienti.csv')
  )
  REJECT LIMIT UNLIMITED;
  
select * from PROJECTSIA.PACIENTI_TABLE ;


--drop table PROJECTSIA.SPITALE_TABLE;
CREATE TABLE PROJECTSIA.SPITALE_TABLE 
( SPITAL_ID         NUMBER  (4) ,
  NUME_SPITAL       VARCHAR2(130),
  ORAS_ID           NUMBER  (4) ,
  INVESTIGATOR_ID   NUMBER  (4) )
ORGANIZATION EXTERNAL
  (  TYPE ORACLE_LOADER
     DEFAULT DIRECTORY TRIALS
     ACCESS PARAMETERS 
       (RECORDS DELIMITED BY NEWLINE 
           NOBADFILE
           NODISCARDFILE
           NOLOGFILE
           FIELDS TERMINATED BY ','
           MISSING FIELD VALUES ARE NULL
       )
     LOCATION ('Spitale.csv')
  )
  REJECT LIMIT UNLIMITED;
  
select * from PROJECTSIA.SPITALE_TABLE;
